CREATE TABLE Ecare_Kiosk_Clients (
  Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
  Name NVARCHAR(120) NOT NULL,
  SapOk BIT NOT NULL
);

CREATE TABLE Ecare_Kiosk_Drivers (
  Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
  Slv NVARCHAR(50) NOT NULL UNIQUE,
  FirstName NVARCHAR(60) NOT NULL,
  LastName NVARCHAR(60) NOT NULL,
  Plate NVARCHAR(30) NOT NULL,
  ClientId UNIQUEIDENTIFIER NULL REFERENCES Ecare_Kiosk_Clients(Id)
);

CREATE TABLE Ecare_Kiosk_Lines (
  Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
  Name NVARCHAR(80) NOT NULL,
  Type INT NOT NULL,
  Capacity INT NOT NULL,
  Occupied INT NOT NULL DEFAULT 0,
  Status INT NOT NULL
);

CREATE TABLE Ecare_Kiosk_Orders (
  Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
  Number NVARCHAR(40) NOT NULL UNIQUE,
  DriverId UNIQUEIDENTIFIER NOT NULL REFERENCES Ecare_Kiosk_Drivers(Id),
  ClientId UNIQUEIDENTIFIER NOT NULL REFERENCES Ecare_Kiosk_Clients(Id),
  ProductId INT NOT NULL,
  ProductType INT NOT NULL,
  ProductName NVARCHAR(120) NOT NULL,
  Unit NVARCHAR(20) NOT NULL,
  Quantity DECIMAL(18,3) NOT NULL,
  Status INT NOT NULL,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE Ecare_Kiosk_Weighings (
  Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
  OrderId UNIQUEIDENTIFIER NOT NULL REFERENCES Ecare_Kiosk_Orders(Id),
  Stage INT NOT NULL,
  GrossKg INT NOT NULL,
  TareKg INT NOT NULL,
  NetKg INT NOT NULL,
  TakenAt DATETIME2 NOT NULL
);

CREATE TABLE Ecare_Kiosk_BonLivraison (
  Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
  OrderId UNIQUEIDENTIFIER NOT NULL REFERENCES Ecare_Kiosk_Orders(Id),
  BlNumber NVARCHAR(40) NOT NULL UNIQUE,
  NetKg INT NOT NULL,
  IssuedAt DATETIME2 NOT NULL
);

-- Seeds
DECLARE @c1 UNIQUEIDENTIFIER = NEWID();
INSERT INTO Ecare_Kiosk_Clients(Id,Name,SapOk) VALUES (@c1,'VADINA',1);

DECLARE @d1 UNIQUEIDENTIFIER = NEWID();
INSERT INTO Ecare_Kiosk_Drivers(Id,Slv,FirstName,LastName,Plate,ClientId) VALUES
(@d1,'13210.B.7','Youssef','H.','20157.E.6',@c1);

INSERT INTO Ecare_Kiosk_Orders (Id,Number,DriverId,ClientId,ProductId,ProductType,ProductName,Unit,Quantity,Status,CreatedAt)
VALUES (NEWID(),'CMD-240915-001',@d1,@c1,3,3,'CIMENT CPJ45 SAC PALETTES','Tonnes',20,1,SYSUTCDATETIME());
